### PR TITLE
pep8

### PR DESCRIPTION
**Pull request by spookybear0**

### CODE REVIEW

**Comment by FigmentBoy** [comment]
Not gonna merge at its current state: 

Requests is in the requirements.txt to enforce the specific version in case of breaking changes down the line.

keyboardinterrupt is purposefully not ignored and all other changes only change the syntax and add nothing to the actual function so are not going to be added

**Comment by FigmentBoy** [comment]
Again this just changes syntax and not function, probably not going to merge

**Comment by spookybear0** [comment]
theres no reason to not merge, this, even if it just updates syntax, it makes the code more readable and up to pep8 standards.

**Comment by FigmentBoy** [comment]
I mean pep8 standards aren't exactly the most important thing ever on a simple and quick project like this; One file with 68 lines isn't the most difficult to understand imo

**Comment by spookybear0** [comment]
what im saying is that, why not have pep 8 compliant files.

**Pull request closed without merging**
